services:
  - type: web
    name: cefr-python-scorer
    env: python
    plan: free
    region: oregon
    buildCommand: python --version && pip install --upgrade pip==23.3.2 setuptools==69.0.2 wheel==0.42.0 && pip install -r requirements.txt --only-binary=all
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1