services:
  - type: web
    name: cefr-python-scorer
    env: python
    plan: free
    region: oregon
    buildCommand: |
      echo "=== Checking Python Version ==="
      python --version
      echo "=== Installing dependencies ==="
      pip install --upgrade pip==23.3.2
      pip install --no-cache-dir --only-binary=all -r requirements.txt
      echo "=== Build Complete ==="
    startCommand: |
      echo "Starting with Python version:"
      python --version
      python -c "import sys; print(f'Python executable: {sys.executable}')"
      python main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: NIXPACKS_PYTHON_VERSION
        value: "3.11.7"